name: Integracion continua de la documentacion

on:
  push:
  pull_request:

jobs:
  construir-documentacion:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar MkDocs
        run: pip install mkdocs

      - name: Construir la documentacion
        run: mkdocs build --strict
